name: ui
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - pkgs/main
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - xarray
  - dask
  - distributed
  - matplotlib
  - scipy
  - scikit-image
  - scikit-learn
  - statsmodels
  - numba
  - networkx
  - sparse
  - zarr
  - rechunker
  - tifffile
  - pyfftw
  - pymetis
  - cvxpy
  - simpleitk
  - medpy
  - ffmpeg
  - ffmpeg-python
  - pyqt
  - requests
  - pyyaml
  - natsort
  - tqdm
  - ipykernel
  - jupyterlab
  - pip:
    - opencv-python
