name: ui # 根据你的环境名称进行修改
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - bokeh=1.4.0
  - cvxpy>=1.1.11
  - dask=2021.2.0
  - datashader=0.12.1
  - distributed=2021.2.0
  - ecos>=2.0.7
  - ffmpeg-python=0.2.0
  - holoviews=1.12.7
  - jupyter
  - matplotlib
  - natsort
  - netcdf4
  - networkx=2.4
  - numba=0.52.0
  - numpy=1.20.2
  - pandas=1.2.3
  - panel=0.8.0
  - pyfftw=0.12.0
  - scikit-image=0.18.1
  - scikit-learn=0.22.1
  - scipy>=1.4.1
  - scs
  - simpleitk=2.0.2
  - sk-video
  - statsmodels>=0.11.1
  - tifffile
  - xarray=0.17.0
  - zarr
  - sparse=0.11.2
  - pymetis=2020.1
  - rechunker=0.3.3
  - medpy=0.4.0
  - jinja2=2.11.3
  - sphinx=3.5.3
  - pydata-sphinx-theme=0.5.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - beautifulsoup4
  - nbsphinx=0.8.7
  - docutils=0.16
  - m2r2=0.2.7
  - markupsafe=2.0.1